name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'
      - 'components/**'
      - 'pages/**'
      - 'app/**'
      - 'public/**'
      - 'styles/**'
      - 'next.config.js'
      - 'package.json'
      - 'package-lock.json'
      - 'Dockerfile'
      - '.github/workflows/build-and-deploy-to-azure-app-service.yaml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ACR_NAME: resmatchaacr
  ACR_REGISTRY_URL: resmatchaacr.azurecr.io
  IMAGE_NAME: resmatcha-frontend
  RESOURCE_GROUP: rg-resmatcha-frontend
  APP_NAME: resmatcha-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Azure using service principal credentials
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Verify ACR exists and get subscription info
      - name: Verify ACR and subscription
        run: |
          echo "Current subscription:"
          az account show --query "{name:name, id:id}" -o table
          echo "Checking if ACR exists..."
          az acr show --name ${{ env.ACR_NAME }} --query "{name:name, resourceGroup:resourceGroup}" -o table

      # Step 4: Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      # Step 5: Build and push Docker image to ACR
      - name: Build and Push Docker image to ACR
        run: |
          docker build -t ${{ env.ACR_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker tag ${{ env.ACR_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.ACR_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.ACR_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.ACR_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest

      # Step 6: Get service principal credentials from Azure context
      - name: Get service principal credentials
        id: sp-creds
        run: |
          # Extract service principal ID from the Azure context
          SP_ID=$(az account show --query user.name -o tsv)
          echo "Service Principal ID: $SP_ID"
          echo "SP_ID=$SP_ID" >> $GITHUB_OUTPUT

      # Step 7: Configure App Service for container deployment using service principal
      - name: Configure App Service for Container
        run: |
          # Use service principal authentication instead of admin credentials
          az webapp config container set \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.APP_NAME }} \
            --docker-custom-image-name ${{ env.ACR_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --docker-registry-server-url https://${{ env.ACR_REGISTRY_URL }}

      # Step 8: Configure container registry authentication using managed identity
      - name: Configure ACR authentication for App Service
        run: |
          # Get the service principal details from the secret
          CLIENT_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientId')
          CLIENT_SECRET=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.clientSecret')
          
          # Configure App Service to use service principal for ACR access
          az webapp config appsettings set \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.APP_NAME }} \
            --settings \
              DOCKER_REGISTRY_SERVER_URL=https://${{ env.ACR_REGISTRY_URL }} \
              DOCKER_REGISTRY_SERVER_USERNAME=$CLIENT_ID \
              DOCKER_REGISTRY_SERVER_PASSWORD=$CLIENT_SECRET

      # Step 9: Set application environment variables
      - name: Configure App Settings
        run: |
          az webapp config appsettings set \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.APP_NAME }} \
            --settings \
              NODE_ENV=production \
              NEXT_TELEMETRY_DISABLED=1 \
              PORT=3000 \
              WEBSITES_PORT=3000 \
              NEXT_PUBLIC_API_URL="${{ secrets.NEXT_PUBLIC_API_URL || 'https://api.resmatcha.com' }}" \
              NEXT_PUBLIC_APP_NAME="ResMatcha" \
              NEXT_PUBLIC_ENVIRONMENT="${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}"

      # Step 10: Restart the app to pull new container
      - name: Restart App Service
        run: |
          az webapp restart \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.APP_NAME }}

      # Step 11: Azure logout
      - name: Azure logout
        run: az logout
        if: always()